// ── MOVIES ──
const movies = [
  { title: "Oppenheimer",        year: "2023", genre: ["Drama","History"],    emoji: "💣" },
  { title: "Dune: Part Two",     year: "2024", genre: ["Sci-Fi","Epic"],      emoji: "🪱" },
  { title: "Poor Things",        year: "2023", genre: ["Fantasy","Drama"],    emoji: "⚗️" },
  { title: "Past Lives",         year: "2023", genre: ["Romance","Drama"],    emoji: "🌿" },
  { title: "The Zone of Interest",year:"2023", genre: ["Drama"],              emoji: "🌸" },
  { title: "Killers of the Flower Moon", year:"2023", genre:["Crime","Drama"],emoji: "🌻" },
  { title: "Spider-Man: Across the Spider-Verse", year:"2023", genre:["Animation","Action"], emoji:"🕷️" },
  { title: "Alien: Romulus",     year: "2024", genre: ["Sci-Fi","Horror"],    emoji: "👾" },
];

// ── TV SHOWS ──
const tvShows = [
  { title: "Shogun",             year: "2024", genre: ["Drama","History"],    emoji: "⚔️" },
  { title: "The Bear",           year: "2024", genre: ["Drama","Comedy"],     emoji: "🐻" },
  { title: "House of the Dragon",year: "2024", genre: ["Fantasy","Drama"],    emoji: "🐉" },
  { title: "Fallout",            year: "2024", genre: ["Sci-Fi","Action"],    emoji: "☢️" },
  { title: "Severance",          year: "2022", genre: ["Sci-Fi","Thriller"],  emoji: "🏢" },
  { title: "Abbott Elementary",  year: "2023", genre: ["Comedy"],             emoji: "🏫" },
];

// ── PROXY QUICK HINTS ──
const proxyHints = [
  "google.com","youtube.com","reddit.com","wikipedia.org","github.com",
];

// ── UGS GAME LIST ──
// Raw filenames as stored on CDN — the 'cl' prefix is stripped in display only.
// Fetched from: https://cdn.jsdelivr.net/gh/bubbls/ugs-singlefile/UGS-Files/
const ugsFiles = [
  'cl1','cl10bullets','cl10minutestildawn','cl12minibattles','cl1on1soccer',
  'cl1v1lol','cl1v1tennis','cl2048','cl2048cupcakes','cl2doom','cl2Dshooting',
  'cl3dash','cl3pandas','cl3pandasbrazil','cl3pandasfantasy','cl3pandasjapan',
  'cl3pandasnight','cl3slices2','cl40xescape','cl4thandgoal','cl500calibercontractz',
  'cl60secondsburgerrun','cl60secondssantarun','cl8ballclassic','cl8ballpool',
  'cl9007199254740992','cl99balls','cl99nightsitf','clabandoned3','clabsolutemadness',
  'clacecombat2','clacecombat3','clacegangstertaxi','clachievementunlocked',
  'clachievmentunlocked','clachievmentunlocked2','clachievmentunlocked3','clachillies',
  'clachillies2','clADarkRoom','cladayintheoffice','clADOFAI','cladvancewars',
  'cladvancewars2','cladventneon','clAdventureCapatalist','cladventurecapitalist',
  'clagariolite','clageofwar','clageofwar2','clagesofconflict','clahoysurvival',
  'clai','clakoopasrevenge','clakoopasrevenge2','clakumanorgaiden','clalienhominid',
  'clalienhominidgba','clalienskyinvasion','clalientransporter','clalienvspredator',
  'clallbossesin1','clallocation','clamaze','clamidstthesky','clamigopancho',
  'clamigopancho2','clamigopancho3','clamigopancho4','clamigopancho5','clamigopancho6',
  'clamigopancho7','clamongus','clamorphous','clancientsins','clangrybirds',
  'clangrybirdsshowdown','clangrybirdsspace','clanimalcrossingwildworld','clanotherworld',
  'clapotris','clappleshooter','clappleworm','claquaparkio','clarceuslegend',
  'clarcheryworldtour','clarena','clarmormayhem2','clarsonate','clascent',
  'clasmallworldcup','clasteroids','clasteroidsALT','clattackhole','clavalanche',
  'claviamasters','clawesomeplanes','clawesometanks','clawesometanks2',
  'clbabeltower','clbabychiccoadventure','clbabykaizo','clbabysniperinvietnam',
  'clbackrooms','clbackrooms2D','clbackyardbaseball','clbackyardbaseball09',
  'clbackyardbaseball10','clbackyardsoccer','clbaconmaydie','clbadbodyguards',
  'clbadicecream','clbadmondaysimulator','clbadparenting','clbadpiggies',
  'clbadtimesimulator','clbaldisbasics','clbaldisbasicsremaster','clballblast',
  'clballsandbricks','clbananasimulator','clbanditgunslingers','clbanjokazooie',
  'clbanjotooie','clbarryhasasecret','clbaseballbros','clbasketballfrvr',
  'clbasketballlegends','clbasketballstars','clbasketbattle','clbasketbros',
  'clbasketrandom','clbasketslamdunk2','clbatterup','clbattlekarts','clbattles',
  'clbattlesim','clbattlezone','clbazookaboy','clbballlegend','clbeachboxingsim',
  'clbearbarians','clbearsus','clben10alienforce','clben10omniverse','clben10protector',
  'clben10racing','clben10ultimatealien','clbfdia5b','clbigicetowertinysquare',
  'clbigneontowertinysquare','clbigshotboxing2','clbigtowertinysquare',
  'clbigtowertinysquare2','clbindingofisaccsheeptime','clbioevil4','clbitlife',
  'clbitplanes','clblackjack','clblackjackbattle','clblacksmithlab','clblastronaut',
  'clblazedrifter','clbleachvsnaruto','clblightborne','clblobsstory2','clblockblast',
  'clblockcraftparkour','clblockcraftshooter','clblockpost','clblockthepig',
  'clblockydemolitionderby','clblockysnakes','clbloodmoney','clbloodtournament',
  'clbloons','clbloons2','clbloonspp1','clbloonspp2','clbloonspp3','clbloonspp4',
  'clbloonspp5','clbloonsTD1','clbloonsTD2','clbloonsTD3','clbloonsTD4','clbloonsTD5',
  'clbloonsTD6scratch','clbloxorz','clBMX2','clbobtherobber','clbobtherobber2',
  'clbobtherobber5','clbollybeat','clbomberman','clbomberman2','clbombermanhero',
  'clboomslingers','clbottleflip3d','clbounceback','clbouncemasters','clbouncymotors',
  'clBountyOfOne','clboxhead2playrooms','clboxheadnightmare','clboxinglive2',
  'clboxingrandom','clbrainrot','clbridgerace','clBTD1','clbtd5','clbubbleshooter',
  'clbubbleshooterpirate','clbubbletanks','clbubbletanks2','clbubbletanks3',
  'clbubbletanksarenas','clbubbletankstd','clbuckshotroulette','clbuildnowgg',
  'clbunnyland','clburgerandfrights','clburritobison','clburritobison2',
  'clburritobisonlaunchalibre','clburritobisonrevenge','clbushidoblade',
  'clcactusmccoy','clcactusmccoy2','clcannonballs3d','clcannonfodder',
  'clcapybaraclicker','clcarcrash3','clcardrawing','clcareatscar2deluxe',
  'clcarkingarena','clcarmods','clcarstuntsdriving','clcastlebloodline',
  'clcastlecircleofmoon','clcastlevania','clcastlevania2','clcastlevania3',
  'clcastlevaniaariaofsorrow','clcastlevaniadawnofsorrow','clcastlevanianes',
  'clcastlewarsmodern','clcatmario','clcatslovecake2','clcavestory','clceleste',
  'clceleste2','clcellardoor','clchaosfaction2','clcheckers','clcheesechompers3d',
  'clcheshireinachatroom','clchess','clchessclassic','clchibiknight','clchickenscream',
  'clchickenwar','clchipschallenge','clchoppyorc','clchronotrigger','clchuzzle',
  'clCircloO2','clciviballs','clciviballs2','clclashofvikings','clclassof09',
  'clcleanupio','clclearvision','clclearvision2','clclearvision3','clclearvision4',
  'clclearvision5','clclmadnessambulation','clclubbytheseal','clclusterrush',
  'clcod4','clcodblackopp','clcoddefiance','clcodenamegordon','clcodmodernwarfare',
  'clcodworldatwar','clcoffeemaker','clcolorburst3d','clcolormatch',
  'clcolorwatersort3d','clcombopool','clcommanderkeen4','clcommanderkeen5',
  'clcommanderkeen6','clconkersbadfurday','clcontra','clcontra3','clcookieclicker',
  'clcookingmama','clcookingmama2','clcookingmama3','clcoreball','clcotlk',
  'clcountmastersstickmangames','clcoverorange','clcoverorange2',
  'clcoverorangejourneygangsters','clcoverorangejourneyknights',
  'clcoverorangejourneypirates','clcoverorangejourneyspace',
  'clcoverorangeplayerspack','clcoverorangeplayerspack2','clcoverorangeplayerspack3',
  'clcrashbandicoot','clcrashbandicoot2','clcrashteamracing','clcrazycars',
  'clcrazycattle3d','clcrazychicken3D','clcrazyfrogracer','clcrazymotorcycle',
  'clcreeperworld2','clcrossyroad','clcrunchball3000','clcs1.6','clcurveball',
  'clcuttherope','clcuttheropetimetravel','clcyberbungracing','clcybersensation',
  'cldadgame','cldaggerfall','cldanktomb','cldborigins','cldborigins2','cldbsniper',
  'cldbzattacksaiyans','cldbzdevolution','cldeadestate','cldeadlydescent',
  'cldeadplate','cldeadzed','cldeadzed2','cldeathchase','cldeblob2','cldecision',
  'cldecision2','cldecision3','cldecisionmedieval','cldeepersleep','cldeepestsword',
  'cldeepsleep','cldefendyourcastle','cldefendyournuts','cldefendyournuts2',
  'cldeltarune','cldementium','cldemolitionderbycrashracing','cldiablo',
  'cldiamondhollow','cldiamondhollow2','cldiddykong-racing','cldieinthedungeon',
  'cldigdeep','cldigdug','cldigdug2','cldigtochina','cldinodudes','cldiredecks',
  'cldoblox','cldogeminer','cldogeminer2','cldokidokiliteratureclub','cldonkeykong',
  'cldonkeykong64','cldonkeykongcountry','cldonkeykongcountry2','cldonkeykongcountry3',
  'cldontescape','cldontescape2','cldontescape3','cldoodlejump','cldoom','cldoom2',
  'cldoom2d','cldoom64','cldoomzio','cldouchebaglife','cldouchebagworkout',
  'cldownthemountain','cldragonballadvance','cldrawclimber','cldrawtheline',
  'cldreadheadparkour','cldriftboss','cldrifthuntersmerge','cldrivemady',
  'cldrmario','cldubstep','clduckhunt','clducklife','clducklife2','clducklife3',
  'clducklife4','clducklifebattle','clducklifespace','clducktales','cldukenukem3d',
  'cldungeondeck','cldungeonraid','cldungeonsanddegenerategamblers','cldunkshot',
  'clduskchild','cldyingdreams','cldynamiteheaddy',
  'cleagleride','clearntodie','clearntodie2','clearthbound','clearthboundsnes',
  'clearthtaken','clearthtaken2','clearthtaken3','clearthwormjim','clearthwormjim2',
  'cledelweiss','cleffinghail','cleffingmachines','cleffingworms','cleffingzombies',
  'clegg','cleggycar','clelectricman2','clendlesswar4','clendlesswar5','clendlesswar7',
  'clepicbattlefantasy5','clescalatingduel','clescaperoad','clet','clevilglitch',
  'clevolution','clexcitebike64','clextremerun3d',
  'clfactoryballs','clfactoryballs2','clfactoryballs3','clfactoryballs4',
  'clfairytalevsonepiece','clfallout','clfamidash','clfancypantsadventure',
  'clfancypantsadventure2','clfancypantsadventure3','clfancysnowboarding',
  'clfattygenius','clfearstofathomhomealone','clfeedus','clfeedus2','clfeedus3',
  'clfeedus4','clfeedus5','clFF3','clff6','clffmysticquest','clfinalearth2',
  'clfinalfantasy','clfinalfantasyII','clfinalfantasytactics','clfinalfantasyVI',
  'clfinalfantasyVII','clfinalninja','clfireblob','clfireboyandwatergirl',
  'clfireboyandwatergirl2','clfireboyandwatergirl3','clfireboyandwatergirl5',
  'clfireboyandwatergirl6','clfireemblem','clfisheatgettingbig','clfisquarium',
  'clfivenightsatbaldisredone','clfivenightsatshrekshotel','clflashsonic',
  'clfloodrunner','clfloodrunner2','clfloodrunner4','clfluidism',
  'clFNAF','clFNAF2','clFNAF3','clFNAF4','clfnafanimatronics','clfnafps','clfnafsl',
  'clfnafucn','clfnafworldd','clfnfagoti','clfnfbfdi26','clfnfblackbetrayal',
  'clfnfbside','clfnfcamelliarudeblaster','clfnfcrunchin','clfnfdesolation',
  'clfnfdokitakeoverplus','clfnfdropandroll','clfnfdustin','clfnffleetway',
  'clfnffnaf3','clfnfgamebreakerbundle','clfnfgoldenapple','clfnfhex','clfnfholiday',
  'clfnfhorkglorpgloop','clfnfhypnoslullaby','clfnfimposterv4','clfnfindiecross',
  'clfnfmadnesspoop','clfnfmariomadnessdside','clfnfmidfight','clfnfmiku',
  'clfnfmobmod','clfnfneo','clfnfpiggyfield','clfnfpokepastaperdition','clfnfqt',
  'clfnfrevmixed','clfnfrewrite','clfnfselfpaced','clfnfshaggy4keys','clfnfshaggyxmatt',
  'clfnfshucksv2','clfnfsky','clfnfsoft','clfnfsonicexe','clfnfsonicexe4',
  'clfnftailsgetstrolled','clfnftricky','clfnfwhitty','clfnfzardy',
  'clfocus','clfolderdungeon','clfootballbros','clfootballlegends','clforknsausage',
  'clfortzone','clfpa4p1','clfpa4p2','clfreerider','clfreerider2','clfreerider3',
  'clfridaynightfunkin','clfromrusttoash','clfruitninja','clfunnybattle',
  'clfunnybattle2','clfunnymadracing','clfunnyshooter2','clfzero','clfzerox',
  'clgalaga','clgangstabean','clgangstabean2','clgangsterbros','clgarcello',
  'clgdlite','clgdsubzero','clgeneralchaos','clgeometrydashscratch','clgeometryvibes',
  'clgetawayshootout','clgetontop','clgetyoked','clghosttrick','clgladdihoppers',
  'clgloryhunters','clgoalsouthafrica','clgobble','clgoingballs','clgolddiggerfrvr',
  'clgoldeneye007','clgoldensun','clgoldminer','clgolforbit','clgolfsunday',
  'clgoodboygalaxy','clgoogledino','clgorescriptclassic','clgrandactionsimulator-ny',
  'clgranddad','clgrandtheftautoadvance','clgranny','clgranny2','clgranny3',
  'clgranturismo','clgranturismo2','clgrassmowing','clgravity','clgrimacebirthday',
  'clgrindcraft','clgrowagarden','clgrowyourgarden','clgta','clgta2',
  'clguesstheiranswer','clgunblood','clguncho','clgunknight','clgunmayhem',
  'clgunmayhem2','clgunmayhemredux','clgunnight','clgunsmoke','clgymstack',
  'clhajimeippo','clhalflife','clhalocombatdevolved','clhanger2','clhappyroom',
  'clhappywheels','clhardwaretycoon','clharvestmoon','clharvestmoon64',
  'clhauntthehouse','clheartandsoul','clhelixjump','clhero3flyingrobot','clhextris',
  'clhighstakes','clhighwayracer2','clhighwaytraffic3d','clhillclimbracinglite',
  'clhipsterkickball','clhobo','clhobo2','clhobo3','clhobo4','clhobo5','clhobo6',
  'clhobo7','clhobovszombies','clholeio','clhollowknight','clhouseofhazards',
  'clhoverracerdrive','clhungryknight','clhungrylamu',
  'clicedodo','clicypurplehead','clidlebreakout','clidledice','clidleidlegamedev',
  'clidleminertycoon','climpossiblequiz','climpossiblequiz2','clinfinitecraft',
  'clinkgame','clinnkeeper','clinteractivebuddy','clintrusion','cliqball',
  'clironsnout','clironsoldier',
  'cljacksmith','cljailbreakobbbobob','cljellydadhero','cljellydrift','cljellytruck',
  'cljetpackjoyride','cljetrush','cljetskiracing','cljohnnytrigger','cljohnnyupgrade',
  'cljourneydownhill','cljustfalllol','cljustoneboss',
  'clkaizomarioworld','clkalikan','clkapi','clkaratebros','clkarlson','clkartbros',
  'clkillerinstinct','clkillover','clkingdomheartsdays','clkingdomheartsrecoded',
  'clkirby64','clkirbyandtheamzingmirror','clkirbysadventure','clkirbysdreamland',
  'clkirbysdreamland3','clkirbysqueaksquad','clkirbysuperstar','clkirbysuperstarultra',
  'clkittencannon','clknifehit','clknightmaretower','clkonkrio','clkoopasrevenge',
  'clkourio',
  'cllaststand','cllaststand2','clleaderstrike','cllearntofly','cllearntofly2',
  'cllearntofly3','cllearntoflyidle','cllegobatman','cllegobatman2superheroes',
  'cllegoindianajones','cllegoindianajones2','cllegoninjago','cllegostarwars',
  'cllemmings','clleveldevil','clleverwarriors','cllightitup','cllilrunmo',
  'cllinerider','cllinktothepast','cllittlerunmo','cllockthedoor','clloderunner',
  'cllonewolf','cllosangelesshark','cllowknight','clloz1','cllozlinkawakening',
  'cllozminishcap','cllozoracleofseasons','cllozspirittracks','clluckyblocks',
  'clmadalinstuntcars','clmadalinstuntcarsmultiplayerfixed','clmadnessaccelerant',
  'clmadnesscombatdefense','clmadnesscombatnexus','clmadnessgemini',
  'clmadnesshydraulic','clmadnessinteractive','clmadnessoffcolor',
  'clmadnesspremediation','clmadnessretaliation','clmadnesss2010','clmadnessstand',
  'clmadskillsmotocross2','clmadstuntcars2','clmagictiles3','clmajorasmask',
  'clmakesureitsclosed','clmanagod','clmario3','clmarioandluigisuperstarsaga',
  'clmariocombat','clmariogolf','clmariokart64','clmariokartds',
  'clmariokartsupercircuit','clmariomadness','clmariopaint','clmarioparty',
  'clmarioparty2','clmarioparty3','clmariopartyds','clmariosmysterymeat',
  'clmariotennis','clmaskedforcesunlimited','clmastermindworldconquerer',
  'clmatrixrampage','clmcraerally','clmeatboy','clmeatboyflash','clmedalofhonor',
  'clmedievalshark','clmedievil','clmegachess','clmegaman','clmegaman2','clmegaman3',
  'clmegaman4','clmegaman5','clmegaman6','clmegaman7','clmegaman8','clmegamanlegends',
  'clmegamanlegends2','clmegamanx','clmegamanx2','clmegamanx3','clmegamanx4',
  'clmegamanzero','clmegamanzx','clmegaminer','clmelonplayground','clmeowuwu',
  'clmergeroundracers','clmetalgear','clmetalgearsolid','clmetalslugadvance',
  'clmetalslugmission1','clmetalslugmission2','clmetroid','clmetroid2',
  'clmetroidfusion','clmetroidzeromission','clmiamishark','clmicromages',
  'clmightyknight','clmightyknight2','clmimic','clmindscape','clmineshooter',
  'clminesweeperplus','clminhero','clminicrossword','clminimart','clminishooters',
  'clminitooth','clmiraginewar','clmisslecommand','clmmwilywars','clmobcontrolhtml5',
  'clmobiusrevolution','clmoneyrush','clmonkeymart','clmonstertracks',
  'clmonstertruckportstunt','clmortalkombat','clmortalkombat2','clmortalkombat3',
  'clmortalkombatadvance','clmortkom4','clmotherload','clmotox3m2','clmotox3m3',
  'clmotox3mm','clmotox3mpoolparty','clmotox3mspookyland','clmotox3mwinter',
  'clmountainbikeracer','clmrracer','clmspacman','clmultitask','clmutilate-a-doll',
  'clmyfriendpedro','clmyfriendpedroarena',
  'clnarc','clnaturalselection','clNBAjam','clnbajamTE','clneonblaster','clneonrider',
  'clnetattack','clneverendinglegacy','clnewgroundsrumble','clnewsupermariobros',
  'clnewyorkshark','clnflblitz','clnfscarbonowncity','clnfsmostwanted',
  'clnfsunderground','clnfsunderground2','clngon','clnickelodeonsuperbrawl2',
  'clnightclubshowdown','clnightfire','clnightshade','clnimrods','clninjabrawl',
  'clnitromemustdie','clnoobminer','clnotyourpawn','clnplus','clnubbysnumberfactory',
  'clnzp',
  'clobbyonlyup','clobeythegame','clocarinaoftime','clofflineparadise',
  'clomeganuggetclicker','clonebitadventure','clonenightasfreddy','clonepiece',
  'clonepiecefighting','clonlyup','cloperius','cloppositeday','clopposumcountry',
  'clorbofcreation','cloregontrail','closu','clourpleguy','clovo','clovo2',
  'clovodimensions',
  'clpacman','clpacmansuperfast','clpapabakeria','clpapadonut',
  'clpapalouiewhenburgersattack','clpapalouiewhenpizzasattack',
  'clpapalouiewhensundaesattack','clpapapizzagood','clpapapizzamamamia',
  'clpapascheeseria','clpapascupcakeria','clpapasfreezeria','clpapashotdoggeria',
  'clpapaspancakeria','clpapaspastaria','clpapasscooperia','clpapassushiria',
  'clpapastacomia','clpapaswingeria','clpaperio','clpaperio3d','clpaperiomania',
  'clpapermario','clpapermariopromode','clpapermariottyd','clparappatherapper',
  'clparkingfury','clparkingfury2','clparkingfury3','clparkingrush',
  'clpartnersintime','clpeacekeeper','clpeggle','clpenaltykicks','clpenguindiner',
  'clpenguinpass','clpepsiman','clpereelous','clperfectdark','clperfecthotel',
  'clpersona','clpersona2','clphasma','clpheonixjusticeforall',
  'clpheonixrightaceattorny','clpheonixtrialsandyear','clpibbyapocalypse','clpico8',
  'clpico8edu','clpicodriller','clpicohot','clpicolife','clpiconightpunkin',
  'clpicosschool','clpicovsbeardx','clpieceofcake','clpikwip','clpingpongchaos',
  'clpinkbike','clpitfall','clpixelbattlegroundsio','clpixelcombat2',
  'clpixelquestlostidols','clpixelshooter','clpixelspeedrun','clpixelwarfare',
  'clpizzapapa','clpizzatower','clplangman','clplantsvszombies','clplazmaburst',
  'clplinko','clplonky','clpogo3D','clpokeblack','clpokeblack2','clpokeblue',
  'clpokeclassic','clpokecrown','clpokecrystalclear','clpokediamond',
  'clpokeemeraldenhanced','clpokeemeraldexceeded','clpokeemeraldhorizons',
  'clpokefiregold','clpokeflora','clpokegaia','clpokegschronicles','clpokeheartgold',
  'clpokelightplatinum','clpokemegamoemon','clpokemonamnesia','clpokemonclover',
  'clpokemoncrystal','clpokemonemerald','clpokemonemeraldcrest',
  'clpokemonemeraldimperium','clpokemonemeraldkaizo','clpokemonemeraldmini',
  'clpokemonemeraldseaglass','clpokemonenergizedemerald','clpokemonfirered',
  'clpokemonfireredrandomized','clpokemongold','clpokemonkaizoironfirered',
  'clpokemonlazarus','clpokemonleafgreen','clpokemonmodernemerald',
  'clpokemonmysterydungeon','clpokemonquetzal','clpokemonroaringred',
  'clpokemonruby','clpokemonsapphire','clpokemonshinsigma','clpokemonsilver',
  'clpokemonsnap','clpokemonstadium','clpokemontowerdefense',
  'clpokemonultimatefusion','clpokemonunbound','clpokemysteryexplorersofsky',
  'clpokeodyssey','clpokepearl','clpokeperfectfirered','clpokepisces','clpokeplatinum',
  'clpokeplatinumrandomized','clpokerechargedpink','clpokerechargedyellow',
  'clpokered','clpokerocketedition','clpokeruby','clpokescorchedsilver',
  'clpokesoulsilver','clpokethepit','clpoketourmaline','clpokeultraviolet',
  'clpokeunovaemerald','clpokevega','clpokevoltwhite2redux','clpokevoyager',
  'clpokewhite','clpokewhite2','clpokeyellow','clpolicepursuit2','clpoorbunny',
  'clporklike','clportal','clportal2d','clportalflash','clporter','clpossessquest',
  'clpostal','clpou','clpraxisfighterx','clprebronzeage','clprecivilationbronzeage',
  'clprehistoricshark','clprimary','clpullfrog','clpunchout','clpunchthetrump',
  'clpuppethockey','clpushyourluck','clpuyopuyofever','clpvz','clpvz2',
  'clpvz2gardenless','clpyrotoad',
  'clqbert','clquake2','clquake3','clquake64','clqwop',
  'clracemaster3d','clracingarena','clradicalred','clraftwars','clraftwars2',
  'clragdoll-io','clragdollarchers','clragdollhit','clragdollrunners',
  'clragdollsoccer','clraze','clraze2','clraze3','clreachthecore','clrebuild',
  'clrebuild2','clrecoil','clredball','clredball2','clredball3','clredball4',
  'clredball4vol2','clredball4vol3','clredhanded','clredtierunner','clredvsblue2',
  'clredvsbluewar','clreignofcentipede','clrenegades','clresidentevil',
  'clresidentevil2','clretrobowl','clretrobowlcollege','clretrohighway',
  'clretropingpong','clreturnman','clreturnman2','clreturntoriddleschool',
  'clrevolutionidle','clrhythmheaven','clricochetkills2','clriddlemiddleschool',
  'clriddleschool','clriddleschool2','clriddleschool3','clriddletransfer',
  'clriddletransfer2','clridgeracer','clroadfighter','clroadoffury','clroadofthedead',
  'clroadofthedead2','clrocketjump','clrocketknightadventures','clrocketleague',
  'clrocketpult','clrocketsoccerderby','clroguesoul','clroguesoul2','clrollerballer',
  'clrollingsky','clrollyvortex','clrolypolymonster','clrooftopsnipers',
  'clrooftopsnipers2','clroomclicker','clrotate','clrouletteknight','clrun',
  'clrun2','clrun3','clrussiancardriver',
  'clsandboxcity','clsandboxels','clsandsofthecoliseum','clsandtris','clsantarun',
  'clsaszombieassault2','clsaulgoodmanrun','clscarletshift','clscarymazegame',
  'clscrapmetal3','clscrapyarddog','clscribblenauts','clscubabear','clseamongrel',
  'clsecretofmana','clsentryfortress','clserenitrove','clservingupmadness',
  'clsfk','clsfk2','clsfklaststand','clsfkleague','clshaggy','clshift','clshift2',
  'clshift3','clshinmegamitenseidevilsurvivor','clshortlife','clshredmill',
  'clshrubnaut','clsideeffects','clsidepocket','clsierra7','clsilenthill',
  'clsilk','clsixwaystodie','clskateit','clskibidishooter','clskong','clsliceitall',
  'clslideinthewoods','clslimelabratory','clslipways','clslitherio','clslope',
  'clslope2player','clslope3','clslopeplus','clslowroads','clsmashkarts',
  'clsmashremix','clsmbc','clsmbcrossover','clsnailbob','clsnailbob2','clsnailbob3',
  'clsnailbob4space','clsnailbob5lovestory','clsnakeis','clsnakelike',
  'clsnipershot','clsniperv2','clsnowballio','clsnowrider','clsnowroad',
  'clsoccerbros','clsoccerrandom','clsolarsandbox','clsolarsmash','clsolitaire',
  'clsonic3andknuckles','clsonic3complete','clsonic3dblastdx','clsonicadvance',
  'clsonicadvance2','clsonicadvance3','clsonicandknuckles','clsonicbattle',
  'clsoniccd','clsonicgg','clsonicmegamix','clsonicr','clsonicrevert','clsonicrush',
  'clsonicrushadventure','clsonicspinball','clsonicthehedgehog','clsonicthehedgehog2',
  'clsonicthehedgehog3','clsonny2','clsouljumper','clspacebarclicker',
  'clspacecompany','clspaceinvaders','clspaceiskey','clspaceiskey2',
  'clspacewarsbattleground','clspacewaves','clspeedstars','clspewer','clspiralroll',
  'clsprunked','clsprunki','clsprunkiclicker','clsquidplayground','clstackballio',
  'clstacktris','clstackydash','clstarfox','clstarfox64','clstateio','clstation141',
  'clstationmeltdown','clstealthassassin','clstealthmaster','clsteelempire',
  'clsteelsurge','clstickarchersbattle','clstickfighter','clstickjetchallenge',
  'clstickmanandguns','clstickmanclash','clstickmanduel','clstickmangtacity',
  'clstickmanhook','clstickmankombat2d','clstickmanstealingdiamond',
  'clstickmerge','clstickminairship','clstickminbreakingbank','clstickminescapingprison',
  'clstickminfleecomplex','clstickrpgcomplete','clstickslasher','clstickwar',
  'clstickwar2','clstormthehouse','clstormthehouse3','clstreetfighter2',
  'clstreetfighter2turbo','clstreetfighteralpha3','clstreetofrage','clstreetofrage2',
  'clstreetofrage3','clstrikeforceheroes','clstrikeforceheroes2','clstrikeforceheroes3',
  'clstrikerdummies','clstylesavvy','clsubwaysurfersbarcelona','clsubwaysurfersbeijing',
  'clsubwaysurfersberlin','clsubwaysurfersbuenosaires','clsubwaysurfershavana',
  'clsubwaysurfershouston','clsubwaysurfersiceland','clsubwaysurferslondon',
  'clsubwaysurfersmexico','clsubwaysurfersmiami','clsubwaysurfersmonaco',
  'clsubwaysurfersneworleans','clsubwaysurferssanfrancisco','clsubwaysurfersstpetersburg',
  'clsubwaysurferswinterholiday','clsubwaysurferszurich','clsugarsugar','clsuika',
  'clsunandmoon','clsuperbomberman','clsuperbomberman2','clsuperbomberman3',
  'clsuperbomberman4','clsuperbomberman5','clsupercarrush','clsuperchibiknight',
  'clsupercold','clsuperdarkdeception','clsuperfighters','clsuperhot',
  'clsuperhotlinemiami','clsuperhouseofdeadninjas','clsuperkidadventure',
  'clsuperliquidsoccer','clsupermario','clsupermario63','clsupermario64',
  'clsupermario64ds','clsupermarioallstars','clsupermariobros','clsupermariobros2',
  'clsupermariobros3','clsupermariokart','clsupermarioland','clsupermarioland2',
  'clsupermariorpg','clsupermarioworld','clsupermarioworld2','clsupermetroid',
  'clsupermonkeyballjr','clsuperoliverworld','clsuperpickleballadventure',
  'clsuperpunchout','clsuperpuzzlefighter2turbo','clsuperscribblenauts',
  'clsupersmashbros','clsupersmashflash','clsupersmashflash2','clsupertiltbros',
  'clsupremeduelist','clsurvevio','clsurvivalracev2','clsushicat','clsushicat2',
  'clsushiunroll','clswerve','clswitchblade','clswordfight','clswordplay',
  'clswordsandsandals','clswordsandsandals2','clswordsandsouls','clsydneyshark',
  'cltabletanks','cltabletennisworldtour','cltakeover','cltallmanrun','cltankmayhem',
  'cltankpixel','cltanukisunset','cltapper','cltaproad','cltastyplanet',
  'cltecmobowl','cltelephonetrouble','cltempest2000','cltempleofboom','cltemplerun2',
  'clterra','clterritorialio','clterritorywar','cltetris','cltetrisattack',
  'cltetrisgba','cltheclassroom','cltheclassroom2','cltheclassroom3','clthedeadseat',
  'clthedeepestsleep','cltheenchantedcave2','cltheimpossiblegame',
  'cltheincrediblemachine','clthelaststand','clthelaststandunioncity',
  'clthemaninthewindow','clthemepark','clthepit','clthereisnofile',
  'clthisistheonlylevel','clthisistheonlylevel2','clthisistheonlyleveltoo',
  'clthreegoblets','clthrowapotato','clthrowapotatoagain','clthwack',
  'cltimeshooter2','cltimeshooter3','cltimewarriors','cltinyfishing','cltmnt',
  'cltoasterball','cltombofthemass','cltommorowandyesterday','cltomodachicollection',
  'cltonyhawkskater2','cltonyhawkskater4','cltonyhawksunderground','cltopspeedracing3d',
  'cltosstheturtle','cltowerblocks','cltowercrash3d','cltownscraper','cltrace',
  'cltrafficjam3d','cltrapthecat','cltrechoroustrials','cltrechoroustrialspart2',
  'cltripleplay2000','cltriviacrack','cltrollfacequest1','cltrollfacequest2',
  'cltrollfacequest3','cltrollfacequest4','cltrollfacequest5','cltrollfacequest6',
  'cltrollfacequest7','cltrollfacequest8','cltrollfacequest9','cltrollfacequest10',
  'cltrollfacequest11','cltrollfacequest12','cltrollfacequest13','cltrucksim',
  'cltubejumpers','cltunnelrush','clturbostars','cltwinshot',
  'cltwistedmetal','cltwistedmetal2','cltwoball3d',
  'clultimateassassian2','clultimateassassian3','clUltimatecardrivingsimulator',
  'clultimatemortalkombat','clultimatemortalkombat3','clultrakill',
  'cluncannycatgolf','clunderneath','clundertaler','clundertaleyellow',
  'clunfairmario','clunfairundyne','clunicyclehero','cluno','clupgradecomplete',
  'clupgradecomplete2','clupslash',
  'clvampiresurvivors','clvanguard','clvaportrails','clvex','clvex2','clvex3',
  'clvex3xmas','clvex4','clvex5','clvex6','clvex7','clvex8','clvexchallenges',
  'clvillager','clvisitor','clvolleyrandom','clvollyballchallenge','clvvvvvv',
  'clwaluigitacostand','clwarfare1944','clwarioland4','clwariowarediy',
  'clwariowareinc','clwartheknight','clwaterpoolio','clwavedash','clwaverun',
  'clwebecomewhatwebehold','clwebfishing','clweltling','clwhackthetheif',
  'clwhackyourboss','clwhackyourcomputer','clwheeliebike','clwheely','clwheely2',
  'clwheely3','clwheely4','clwheely5','clwheely6','clwheely7','clwheely8',
  'clwindowsdoors','clwinterfalling','clwitchcrafttd','clwolfenstein',
  'clwolfenstein3d','clwoodworm','clwordle','clworldshardestgame',
  'clworldshardestgame2','clworldshardestgame3','clworldshardestgame4',
  'clwrassling','clwrestlebros',
  'clyanderesimulator','clyarsrevenge','clyellow','clyouarelucky','clyumenikki',
  'clzelda2thelegendoflink','clzeldaminishcap','clzenword','clzombieexploder',
  'clzombieroad','clzombierush','clzombiesatemyneighboors','clzombopaclypse2',
  'clzombotron','clzombotron2','clzombotronreboot','clzrist','clzuma','clzumashooter',
  'marbleracer','mariobuilder64','mortalkombat4','polytrackbutnotflagged',
  'rocketknight2','sandstone','snowbros','superdromebugs','vvvvvv','wilywars',
  'Eaglercraft-Alpha-1.2.6-Offline','eaglercraft.1.5.2',
  'EaglercraftX 1.8.8(u29)','EaglercraftZ_1.11.2',
];

// Strip 'cl' prefix and prettify for display
function ugsDisplayName(filename) {
  let name = filename;
  if (/^cl/i.test(name)) name = name.slice(2);
  // split on camelCase, numbers, dashes, underscores
  name = name
    .replace(/([a-z])([A-Z])/g, '$1 $2')   // camelCase -> spaces
    .replace(/[-_]+/g, ' ')                  // dashes/underscores -> spaces
    .replace(/(\d+)/g, ' $1 ')              // pad numbers
    .replace(/\s+/g, ' ')                    // collapse whitespace
    .trim();
  // Title case each word
  name = name.replace(/\b\w/g, c => c.toUpperCase());
  return name || filename;
}
